id: P008199
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W17209
  title: བོད་རིག་པའི་བྱུང་བ་དང་འབྱུང་འགྱུར་སྐོར
  author: ''
  volumes:
    00ab8bb38c934990b7e386a93d725883:
      image_group_id: I4999
      title: ''
      volume_number: 1
      total_pages: 180
      base_file: v001.txt
