id: I559A04A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:22:48+00:00'
last_modified: '2022-06-09T05:11:23.448902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W17209
  title: བོད་རིག་པའི་བྱུང་བ་དང་འབྱུང་འགྱུར་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0AE3:
      image_group_id: I4999
      title: ''
      total_pages: 180
      order: 1
      base_file: 0AE3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
